### ISSUE TITLE
New pxe image

### ISSUE THREAD

**Issue by dreamcat4** [jpetazzo/pxe#14]
Hi Jerome,

https://github.com/jpetazzo/pxe/blob/master/README.md#i-want-to-netboot-something-else

I thought you might be interested to hear some advancements in pxe network booting. To that end I have just finished a new docker image, with the most recent software and advancements in it.

Many thanks for providing the inspiration for making a pxe docker image. Before seeing your one, was not sure if it was even possible!

Can see here:

https://github.com/dreamcat4/docker-images/tree/master/pxe

**Comment by jpetazzo** [comment]
Yay! I linked that from the README.
