### ISSUE TITLE
Add reference to Bridge-NF

### ISSUE THREAD

**Issue by xkjyeah** [jpetazzo/pxe#17]
I had issues setting up the bridge, before I realized that bridge-netfilter filtering must be turned off.

**Symptoms**
- Can ping external server from host
- Can ping DHCP server (in Docker) from host
- Cannot ping host from external server or vice-versa

**Solution**
Disable bridge netfiltering on the host.
```sh
# sysctl -w net.bridge.bridge-nf-call-iptables=0
# sysctl -w net.bridge.bridge-nf-call-ip6tables=0
```

Could you add this as a hint to the README?

**Comment by xkjyeah** [comment]
I am using Ubuntu 16.04, Docker 17.05

**Comment by xkjyeah** [comment]
My uname -a:

Linux daniel-VirtualBox 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18
12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jpetazzo** [comment]
I added a note in the README. Thank you for reporting this!
