### ISSUE TITLE
Docker pull error

### ISSUE THREAD

**Issue by johnarnold** [jpetazzo/pxe#5]
I'm getting an error trying to pull 'latest' -- can you check that you can pull from the docker repo?

root@str-debianpxe:/etc/docker# docker -D pull jpetazzo/pxe
Pulling repository jpetazzo/pxe
055bd4a23971: Error pulling image (latest) from jpetazzo/pxe, HTTP code 400
511136ea3c5a: Download complete
7a1744dd350d: Download complete
dbfa1174cd78: Download complete
e8e1b9d533ad: Error pulling dependent layers
FATA[0014] Error pulling image (latest) from jpetazzo/pxe, HTTP code 400

Other images pull for me (busybox, ubuntu, etc).

Relevant debug log:

DEBU[60604] https://registry-1.docker.io/v1/images/e8e1b9d533ad838823e9a97f00eafad4b9c4a96e7caa353d21d4cf98421e5595/json -- HEADERS: map[User-Agent:[docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.2.0-4-amd64 os/linux arch/amd64]]
DEBU[60604] hostDir: /etc/docker/certs.d/registry-1.docker.io
Error pulling image (latest) from jpetazzo/pxe, HTTP code 400
INFO[60604] -job pull(jpetazzo/pxe, latest) = ERR (1)

Version info:
root@str-debianpxe:/etc/docker# docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
root@str-debianpxe:/etc/docker# docker info
Containers: 0
Images: 9
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 9
Execution Driver: native-0.2
Kernel Version: 3.2.0-4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 1
Total Memory: 996.3 MiB
Name: str-debianpxe
ID: QKD6:OSHB:A3PN:LCBQ:TVLW:B6FU:2QQB:TG6W:5LTH:NSG6:B4U2:PS5H
Debug mode (server): true
Debug mode (client): false
Fds: 11
Goroutines: 16
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No memory limit support
WARNING: No swap limit support

**Comment by jpetazzo** [comment]
Thanks for reporting this.

I've opened a ticket with our internal support team; I'll report here when I hear back from them!

**Comment by jpetazzo** [comment]
Indeed, the image is broken in the registry. I've triggered a rebuild; that should take care of it!
