### ISSUE TITLE
need --privileged

### ISSUE THREAD

**Issue by ag4ve** [jpetazzo/pxe#6]
docker run --privileged -d pxe

**Comment by jpetazzo** [comment]
I would rather use `--add-cap`, if someone can figure out the right flags?

**Comment by avlis** [comment]
or you can just pass --user=root to dnsmasq?

**Comment by barraudf** [comment]
It seems to be working with --cap-add NET_ADMIN

**Comment by avlis** [comment]
it seems to be working fine on pxe_coreos too (without --user=root, dnsmasq running with user 'nobody').

Thanks!

**Comment by jpetazzo** [comment]
If someone wants to submit a PR to update the docs to provide the right flags, I'll be happy to merge it :-)
